### PR TITLE
Fixed logging in a unbounded context

### PR DESCRIPTION
**Pull request by kuutsav**
### **PR Type**
Bug fix

___

### **Description**
- Fixed an indentation issue for a logging statement in the `generate_tests` method of `cover_agent/UnitTestGenerator.py`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>UnitTestGenerator.py</strong><dd><code>Fix logging indentation in `generate_tests` method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
cover_agent/UnitTestGenerator.py

<li>Fixed indentation issue for logging statement within <code>generate_tests</code> <br>method.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/102/files#diff-19760582d9ede3a799fdbb541ad357b4822682e837bca8365196fba50daf57e3">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by rajpatel8 — APPROVED** [review]

**Review by rajpatel8 — APPROVED** [review]

**Review by barnett-yuxiang — COMMENTED** [review]
It is indeed more reasonable to put it in the position of else.

**Comment by EmbeddedDevops1** [comment]
Good call. Long term plan should be to remove `dry_run` eventually and just inject into the function when calling `tests/test_UnitTestGenerator.py`.

**Comment by EmbeddedDevops1** [comment]
@kuutsav Can you resolve the conflicts or close out the PR?

**Comment by EmbeddedDevops1** [comment]
This logging has been removed from `cover_agent/UnitTestGenerator.py` and moved to `cover_agent/CoverAgent.py`

**Pull request closed without merging**
