### PR TITLE
Add to support openai compatible endpoint 

### PR DESCRIPTION
**Pull request by benedict-lee**
### **User description**
**Problem**
Unable to use an own openai compatible endpoint.
Because it only sets `api-base` if it is ollama or huggingface.

**Solution**
Modify litellm completion to use `api-base` if it is an openai compatible endpoint.

**Usage**
Added usage example to README.md.

___

### **PR Type**
enhancement, documentation

___

### **Description**
- Added support for OpenAI compatible endpoints in the `call_model` method of `AICaller.py`.
- Updated the API base exception logic to include OpenAI compatible endpoints.
- Added a usage example for OpenAI compatible endpoints in the README, including instructions for setting the `OPENAI_API_KEY` and using the `--api-base` option.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>AICaller.py</strong><dd><code>Add support for OpenAI compatible endpoints in API base exception</code></dd></summary>
<hr>
      
cover_agent/AICaller.py

<li>Added condition to check for OpenAI compatible endpoints in <code>call_model</code> <br>method.<br> <li> Modified API base exception logic to include OpenAI compatible <br>endpoints.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/56/files#diff-d94557e610fe5a4d747c06e8ac8d6a0e243e5c50b4df8f624fa1acc7d51f57b0">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README with OpenAI compatible endpoint usage example</code></dd></summary>
<hr>
      
README.md

<li>Added usage example for OpenAI compatible endpoints.<br> <li> Updated documentation to include instructions for setting <br><code>OPENAI_API_KEY</code> and using <code>--api-base</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+10/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
@benedict-lee
i like this PR. the code is cleaner with it 👍

**Comment by EmbeddedDevops1** [comment]
@benedict-lee Thanks for doing this. @mrT23 pointed this out but I forgot to refactor. Glad you beat me to it. 😄.

Thanks @mrT23 for the approval and merge.

**Comment by benedict-lee** [comment]
@mrT23 Thanks for merging this. 
And thank you so much for starting this open source project.

@EmbeddedDevops1 A.. Are you okay? :) 
I've touched it a bit, but I think you have some more solid refactoring to do.

**Pull request merged**
