### PR TITLE
Support Azure OpenAI Service

### PR DESCRIPTION
**Pull request by sangmo-kang**
### **User description**
Ref: https://github.com/Codium-ai/cover-agent/issues/55

___

### **PR Type**
enhancement

___

### **Description**
- Added support for Azure API version in `AICaller`, `CoverAgent`, `UnitTestGenerator`, and `UnitTestValidator` classes.
- Updated command-line interface to include `--api-version` argument for specifying Azure API version.
- Enhanced handling of API base and version for Azure models in the `AICaller` class.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>AICaller.py</strong><dd><code>Add support for Azure API version in AICaller</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/AICaller.py

<li>Added <code>api_version</code> parameter to <code>AICaller</code> class.<br> <li> Updated API base and version handling for Azure models.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/212/files#diff-d94557e610fe5a4d747c06e8ac8d6a0e243e5c50b4df8f624fa1acc7d51f57b0">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>CoverAgent.py</strong><dd><code>Include Azure API version in CoverAgent initialization</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/CoverAgent.py

- Added `api_version` parameter to `CoverAgent` initialization.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/212/files#diff-dac868643df79ec6dfcf446359468a88ba6a6617bb8ffa0139757f0fbf5195b1">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>UnitTestGenerator.py</strong><dd><code>Add Azure API version to UnitTestGenerator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/UnitTestGenerator.py

- Added `api_version` parameter to `UnitTestGenerator` class.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/212/files#diff-19760582d9ede3a799fdbb541ad357b4822682e837bca8365196fba50daf57e3">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>UnitTestValidator.py</strong><dd><code>Support Azure API version in UnitTestValidator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/UnitTestValidator.py

- Added `api_version` parameter to `UnitTestValidator` class.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/212/files#diff-8e82655eb4312e27ba8b876368f619bb3fe73990d9c0ef379959a2b210141252">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>main.py</strong><dd><code>Add command-line argument for Azure API version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/main.py

- Added `--api-version` argument for Azure API version.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/212/files#diff-610f77abc2025129e317ec1f98b3bb375b790b2197ed3f635331cca0a06fd999">+6/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
looks good 👍

**Review by mrT23 — APPROVED** [review]

**Comment by sangmo-kang** [comment]
@mrT23 
I checked that using the AZURE_API_BASE and AZURE_API_VERSION environment variables ensures proper functionality.
But , there could be potential issues when trying to use the `--api-base` option with `--model` prefixed by azure/*, as this might not work as expected. Anyway, since the `--api-base` option already exists, I believe someone will definitely make the same mistake.
From that perspective, I believe that changes related to  `--api-base` (https://github.com/Codium-ai/cover-agent/pull/212/files#diff-d94557e610fe5a4d747c06e8ac8d6a0e243e5c50b4df8f624fa1acc7d51f57b0R75) should be merged, even if changes to `--api_version` may not be essential.
If these changes aren’t merged, at least, an update to the README for Azure OpenAI should be considered to clarify this behavior.

How do you feel about merging changes related to `--api-base` or updating the README? Or do you think both are unnecessary tasks?

**Comment by mrT23** [comment]
@sangmo-kang 
If we can update the readme, and these instructions will be enough to enable running AZURE (and avoid changing the code), I think its the best solution

**Comment by sangmo-kang** [comment]
@mrT23
Thanks for your response.
I close this PR and one the new PR modifying the README.

**Pull request closed without merging**
