### PR TITLE
Update README and gitignore

### PR DESCRIPTION
**Pull request by barnett-yuxiang**
### **User description**
Tool installation instructions and enhance command examples

___

### **PR Type**
documentation

___

### **Description**
- Updated the README file to include `poetry run` prefix for the Python FastAPI example command.
- Added installation instructions for `gocov` and `gocov-xml` tools in the Go example section.
- Improved formatting for better readability and emphasis on key terms.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README with tool installation instructions and command </code><br><code>enhancements.</code></dd></summary>
<hr>
      
README.md

<li>Added <code>poetry run</code> prefix to the Python FastAPI example command.<br> <li> Included installation instructions for <code>gocov</code> and <code>gocov-xml</code> for Go <br>example.<br> <li> Enhanced formatting for better readability.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+10/-4</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by barnett-yuxiang** [comment]
@DedyKredo @network-charles @almog-lv

**Comment by EmbeddedDevops1** [comment]
@barnett-yuxiang Thank you very much for contributing to this community project and helping improve our documentation. I left a comment about the `poetry` command and it looks like you've got an unresolved conflict. Any chance you can take a look at those and then I can approve?

**Comment by barnett-yuxiang** [comment]
@EmbeddedDevops1 

got, you are correct, I have updated the commit as required

**Review by EmbeddedDevops1 — APPROVED** [review]

**Comment by hussam789** [comment]
> <details><summary>Ensure consistent capitalization for the term "Go" in the documentation</summary>
> <hr>
> <p dir="auto"><strong>To ensure consistency and clarity, use the same formatting for the term "Go" as used for <br>"python fastapi". This will make the documentation more uniform and easier to read.</strong></p>
> <p dir="auto"><a href="https://github.com/Codium-ai/cover-agent/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R107-R107">README.md [107]</a></p>
> 
> ```diff
> -For an example using **go** `cd` into `templated_tests/go_webservice`, set up the project following the `README.md`.
> +For an example using **Go** `cd` into `templated_tests/go_webservice`, set up the project following the `README.md`.
>  ```
> 
>     
>   
> <details><summary><b>Suggestion importance[1-10]: 7</b></summary>
> <p dir="auto">Why: The suggestion correctly identifies a consistency issue in the formatting of "Go" compared to "python fastapi", which improves the uniformity of the document.</p>
> </details></details>

@hussam789 fix this

**Comment by hussam789** [comment]
> <details><summary>Ensure consistent capitalization for the term "Go" in the documentation</summary>
> <hr>
> <p dir="auto"><strong>To ensure consistency and clarity, use the same formatting for the term "Go" as used for <br>"python fastapi". This will make the documentation more uniform and easier to read.</strong></p>
> <p dir="auto"><a href="https://github.com/Codium-ai/cover-agent/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R107-R107">README.md [107]</a></p>
> 
> ```diff
> -For an example using **go** `cd` into `templated_tests/go_webservice`, set up the project following the `README.md`.
> +For an example using **Go** `cd` into `templated_tests/go_webservice`, set up the project following the `README.md`.
>  ```
> 
>     
>   
> <details><summary><b>Suggestion importance[1-10]: 7</b></summary>
> <p dir="auto">Why: The suggestion correctly identifies a consistency issue in the formatting of "Go" compared to "python fastapi", which improves the uniformity of the document.</p>
> </details></details>

@hussam789 Fix this !

**Pull request merged**
