### PR TITLE
Support for Branch Coverage

### PR DESCRIPTION
**Pull request by EmbeddedDevops1**
### **PR Type**
enhancement, tests

___

### **Description**
- Enhanced the coverage processing to support branch coverage alongside line coverage.
- Updated logging and reporting to include branch coverage metrics.
- Modified coverage parsing methods to return branch coverage percentages.
- Added and updated tests to validate branch coverage parsing and reporting.
- Enabled branch coverage in lcov commands for C and C++ CLI tests.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CoverAgent.py</strong><dd><code>Add branch coverage logging and reporting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/CoverAgent.py

<li>Enhanced logging to include branch coverage.<br> <li> Updated failure messages to reflect branch coverage.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-dac868643df79ec6dfcf446359468a88ba6a6617bb8ffa0139757f0fbf5195b1">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>CoverageProcessor.py</strong><dd><code>Extend coverage parsing to include branch coverage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/CoverageProcessor.py

<li>Updated parsing methods to include branch coverage.<br> <li> Modified return types to include branch coverage percentages.<br> <li> Enhanced logging for coverage data.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-610c623a5c322b67c9a12fa75021723cc335d4dc3ce4676eb8576a20f3ffd93e">+80/-43</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>UnitTestGenerator.py</strong><dd><code>Track and report branch coverage in tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

cover_agent/UnitTestGenerator.py

<li>Added branch coverage tracking.<br> <li> Updated coverage report to include branch coverage.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-19760582d9ede3a799fdbb541ad357b4822682e837bca8365196fba50daf57e3">+8/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>build_and_test_with_coverage.sh</strong><dd><code>Enable branch coverage in C CLI tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

templated_tests/c_cli/build_and_test_with_coverage.sh

- Enabled branch coverage in lcov commands.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-2e179606ce85ceaf43151f4cc4725a5fd65926bd7446c84719c87ecb8141f78d">+3/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>build_and_test_with_coverage.sh</strong><dd><code>Enable branch coverage in C++ CLI tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

templated_tests/cpp_cli/build_and_test_with_coverage.sh

- Enabled branch coverage in lcov commands.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-f73d12c39db491951568fef9d8f80452d68b20d796e951aa378b0b8c06c74a4b">+3/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_CoverageProcessor.py</strong><dd><code>Add tests for branch coverage parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/test_CoverageProcessor.py

<li>Added tests for branch coverage parsing.<br> <li> Updated existing tests to include branch coverage assertions.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-63a3b2f65d74764f35622a99cfbd946c878c01230cf19bb3befc67d2dbfec0c6">+25/-11</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_UnitTestGenerator.py</strong><dd><code>Validate branch coverage in unit tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/test_UnitTestGenerator.py

- Updated test to include branch coverage validation.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/cover-agent/pull/196/files#diff-6563fc9db12b41fab8c40e7392e78047264cc44e6ed59a95ab1eccbecb84d8ad">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by draialexis** [comment]
@EmbeddedDevops1 Thanks again for working on this.

I got it to run locally and I tested it: cover-agent increased line coverage to 100% and stopped there. 

Is there a new argument I should pass, like `--desired-branch-coverage i` and `--desired-line-coverage j`?

----

I'm going to try to make a small PR, to add some info to the README, for other devs. I'll ping you in it

**Comment by EmbeddedDevops1** [comment]
> @EmbeddedDevops1 Thanks again for working on this.
> 
> I got it to run locally and I tested it: cover-agent increased line coverage to 100% and stopped there.
> 
> Is there a new argument I should pass, like `--desired-branch-coverage i` and `--desired-line-coverage j`?
> 
> I'm going to try to make a small PR, to add some info to the README, for other devs. I'll ping you in it
> 
> UPDATE: The README PR was reviewed and merged

@draialexis Currently there isn't. The previous implementation made it difficult to update and add new data points to the LLM without the potential of introducing a regression. Now that cover_agent  is being refactored, it should be easier for cover_agent to ingest new data and we can include a `--desired-line-coverage` flag to be passed and considered by the LLM. We're working through a few other issues in parallel but we plan to get back to this ASAP.

**Comment by draialexis** [comment]
Sweet! Thanks for the update. 

Refactoring is healthy, I congratulate yall.

I re-read my previous comment and realized some of it was unclear -- rephrasing now in case that's useful:

When I ran this branch of Cover Agent on a source file that already had around 70% line coverage, and around 50% branch coverage, Cover Agent maxed out line coverage and stopped early, leaving branch coverage well below the desired number.

**Comment by EmbeddedDevops1** [comment]
Heads up. I rebased and moved to a new PR: https://github.com/Codium-ai/cover-agent/pull/228

**Pull request closed without merging**
